name: Auto Version Update

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  # Wait for all CI checks to pass before proceeding
  wait-for-checks:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Wait for CI workflows to complete
      run: |
        echo "Waiting for CI workflows to complete..."
        # Wait a bit for workflows to start
        sleep 30

        # Wait for all workflows to complete
        max_attempts=30
        attempt=0

        while [ $attempt -lt $max_attempts ]; do
          echo "Checking workflow status (attempt $((attempt + 1))/$max_attempts)..."

          # Get workflow runs for this commit
          runs=$(gh api repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.head_sha == "${{ github.sha }}" and .name != "Auto Version Update") | {name: .name, status: .status, conclusion: .conclusion}')

          if [ -z "$runs" ]; then
            echo "No workflow runs found yet, waiting..."
            sleep 20
            attempt=$((attempt + 1))
            continue
          fi

          echo "Current workflow status:"
          echo "$runs"

          # Check if all workflows are completed
          pending=$(echo "$runs" | jq -r 'select(.status != "completed")')

          if [ -z "$pending" ]; then
            echo "All workflows completed!"

            # Check if any failed
            failed=$(echo "$runs" | jq -r 'select(.conclusion != "success" and .conclusion != "skipped")')

            if [ -n "$failed" ]; then
              echo "Some workflows failed:"
              echo "$failed"
              exit 1
            fi

            echo "All workflows passed! Proceeding with version update..."
            exit 0
          fi

          echo "Still waiting for workflows to complete..."
          sleep 20
          attempt=$((attempt + 1))
        done

        echo "Timeout waiting for workflows to complete"
        exit 1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Only proceed with version bump and PyPI publishing if all CI checks pass
  auto-version:
    needs: wait-for-checks
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging toml

    - name: Determine version bump type
      id: version-type
      run: |
        # Default to patch version bump
        BUMP_TYPE="patch"
        SKIP_BUMP="false"

        # Check commit messages for version bump indicators
        COMMIT_MSG=$(git log -1 --pretty=%B)

        # Check for skip indicators
        if echo "$COMMIT_MSG" | grep -i -E "(\[skip version\]|\[no version\]|skip version|no version bump)" > /dev/null; then
          SKIP_BUMP="true"
        fi

        # Check for version bump keywords in commit message
        if echo "$COMMIT_MSG" | grep -i -E "(BREAKING CHANGE|major version|major update|breaking:)" > /dev/null; then
          BUMP_TYPE="major"
        elif echo "$COMMIT_MSG" | grep -i -E "(minor version|minor update|feat:|feature:)" > /dev/null; then
          BUMP_TYPE="minor"
        elif echo "$COMMIT_MSG" | grep -i -E "(patch version|patch update|fix:|bugfix:)" > /dev/null; then
          BUMP_TYPE="patch"
        fi

        # Check PR labels if this is a merged PR
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"

          if echo "$PR_LABELS" | grep -i "no-version-bump" > /dev/null; then
            SKIP_BUMP="true"
          elif echo "$PR_LABELS" | grep -i "version:major" > /dev/null; then
            BUMP_TYPE="major"
          elif echo "$PR_LABELS" | grep -i "version:minor" > /dev/null; then
            BUMP_TYPE="minor"
          elif echo "$PR_LABELS" | grep -i "version:patch" > /dev/null; then
            BUMP_TYPE="patch"
          fi
        fi

        echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
        echo "skip_bump=$SKIP_BUMP" >> $GITHUB_OUTPUT
        echo "Determined version bump type: $BUMP_TYPE (skip: $SKIP_BUMP)"

    - name: Get current version and calculate new version
      id: version
      run: |
        python << 'EOF'
        import toml
        import re
        import os
        from packaging.version import Version

        # Read current version from pyproject.toml
        with open('pyproject.toml', 'r') as f:
            config = toml.load(f)

        current_version_str = config['project']['version']
        current_version = Version(current_version_str)

        bump_type = "${{ steps.version-type.outputs.bump_type }}"

        # Calculate new version based on bump type
        if bump_type == "major":
            new_version = Version(f"{current_version.major + 1}.0.0")
        elif bump_type == "minor":
            new_version = Version(f"{current_version.major}.{current_version.minor + 1}.0")
        else:  # patch
            new_version = Version(f"{current_version.major}.{current_version.minor}.{current_version.micro + 1}")

        print(f"Current version: {current_version}")
        print(f"New version: {new_version}")
        print(f"Bump type: {bump_type}")

        # Write to GitHub outputs
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f"current_version={current_version}\n")
            f.write(f"new_version={new_version}\n")
        EOF

    - name: Check if version should be updated
      id: should-update
      run: |
        SHOULD_UPDATE="true"

        # Skip if explicitly requested
        if [ "${{ steps.version-type.outputs.skip_bump }}" = "true" ]; then
          SHOULD_UPDATE="false"
          echo "Skipping version update - explicitly requested"
        fi

        # Skip version update if this commit is already a version bump
        COMMIT_MSG=$(git log -1 --pretty=%B)
        if echo "$COMMIT_MSG" | grep -E "^(Bump version|Release)" > /dev/null; then
          SHOULD_UPDATE="false"
          echo "Skipping version update - this appears to be a version bump commit"
        fi

        echo "should_update=$SHOULD_UPDATE" >> $GITHUB_OUTPUT

    - name: Update version in pyproject.toml
      if: steps.should-update.outputs.should_update == 'true'
      run: |
        python << 'EOF'
        import toml

        # Read and update pyproject.toml
        with open('pyproject.toml', 'r') as f:
            config = toml.load(f)

        config['project']['version'] = "${{ steps.version.outputs.new_version }}"

        with open('pyproject.toml', 'w') as f:
            toml.dump(config, f)

        print(f"Updated version to ${{ steps.version.outputs.new_version }}")
        EOF

    - name: Update version in __init__.py
      if: steps.should-update.outputs.should_update == 'true'
      run: |
        sed -i 's/__version__ = ".*"/__version__ = "${{ steps.version.outputs.new_version }}"/' temporal/__init__.py
        echo "Updated __init__.py version to ${{ steps.version.outputs.new_version }}"

    - name: Update CHANGELOG.md
      if: steps.should-update.outputs.should_update == 'true'
      run: |
        python << 'EOF'
        import datetime

        version = "${{ steps.version.outputs.new_version }}"
        bump_type = "${{ steps.version-type.outputs.bump_type }}"
        current_date = datetime.date.today().strftime("%Y-%m-%d")

        # Determine change type based on bump type
        change_type_map = {
            "major": "### Changed\n- BREAKING CHANGE: Major version update",
            "minor": "### Added\n- New feature added",
            "patch": "### Fixed\n- Bug fixes and improvements"
        }

        change_entry = change_type_map.get(bump_type, "### Fixed\n- Updates and improvements")

        # Read current CHANGELOG
        try:
            with open('CHANGELOG.md', 'r') as f:
                content = f.read()
        except FileNotFoundError:
            content = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n"

        # Insert new version entry after the header
        lines = content.split('\n')
        header_end = 0
        for i, line in enumerate(lines):
            if line.startswith('## [') or (i > 5 and line.strip() == ''):
                header_end = i
                break

        new_entry = [
            f"## [{version}] - {current_date}",
            "",
            change_entry,
            "",
            ""
        ]

        # Insert new entry
        updated_lines = lines[:header_end] + new_entry + lines[header_end:]

        with open('CHANGELOG.md', 'w') as f:
            f.write('\n'.join(updated_lines))

        print(f"Updated CHANGELOG.md with version {version}")
        EOF

    - name: Run tests to ensure everything works
      if: steps.should-update.outputs.should_update == 'true'
      run: |
        pip install -e .
        pip install pytest
        pytest tests/ -x -q

    - name: Create version bump branch and PR
      if: steps.should-update.outputs.should_update == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Create new branch for version bump
        branch_name="version-bump-${{ steps.version.outputs.new_version }}"
        git checkout -b "$branch_name"

        # Commit changes
        git add pyproject.toml temporal/__init__.py CHANGELOG.md
        git commit -m "Bump version to ${{ steps.version.outputs.new_version }}"

        # Push branch
        git push origin "$branch_name"

        # Create PR and auto-merge it
        pr_url=$(gh pr create \
          --title "🔖 Bump version to ${{ steps.version.outputs.new_version }}" \
          --body "$(cat <<'EOF'
        ## Auto Version Bump

        **Type**: ${{ steps.version-type.outputs.bump_type }} version update
        **Version**: ${{ steps.version.outputs.current_version }} → ${{ steps.version.outputs.new_version }}

        ### Changes
        - Updated version in \`pyproject.toml\` and \`temporal/__init__.py\`
        - Updated \`CHANGELOG.md\` with new version entry

        ### After Merge
        This PR will automatically:
        - Create git tag \`v${{ steps.version.outputs.new_version }}\`
        - Build and publish package to PyPI
        - Create GitHub release

        🤖 This PR was created and will be auto-merged by the Auto Version Update workflow.
        EOF
        )" \
          --head "$branch_name" \
          --base main)

        echo "Created PR: $pr_url"

        # Wait a moment for PR to be processed
        sleep 10

        # Auto-merge the version bump PR
        echo "Auto-merging version bump PR..."
        gh pr merge "$pr_url" --squash --delete-branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
