name: Publish Release

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version-bump')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Get version from pyproject.toml
      id: version
      run: |
        python << 'EOF'
        import toml
        import os

        with open('pyproject.toml', 'r') as f:
            config = toml.load(f)

        version = config['project']['version']
        print(f"Version: {version}")

        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f"version={version}\n")
        EOF

    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag "v${{ steps.version.outputs.version }}"
        git push origin "v${{ steps.version.outputs.version }}"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.version.outputs.version }}"
        name: "Release v${{ steps.version.outputs.version }}"
        body: |
          ## Version ${{ steps.version.outputs.version }}

          **Type**: Version update merged via PR

          ### Changes
          See [CHANGELOG.md](https://github.com/hasanatkazmi/temporal-python/blob/main/CHANGELOG.md) for detailed changes.

          ### Installation
          ```bash
          pip install temporal-python==${{ steps.version.outputs.version }}
          ```

          **Full Changelog**: https://github.com/hasanatkazmi/temporal-python/compare/v1.0.19...v${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
